config/routes.rb
Rails.application.routes.draw do

  resources :movies do
  	resources :reviews, only: [:new, :create, :destroy]
  end

  namespace :admin do
  	resources :users, only: [:show, :index]
  end

  resources :admin, only: [:new, :create, :index]

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]

  root to: 'movies#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
	mount_uploader :image, ImageUploader

	has_many :reviews
	validates :title, presence: true

	validates :director, presence: true

	validates :runtime_in_minutes,
						numericality: {only_integer: true}

	validates :description, presence: true

	validates :image, presence: true

	validates :release_date, presence: true

	validate :release_date_is_in_the_past

	def review_average
		reviews.exists? ? (reviews.sum(:rating_out_of_ten)/reviews.size) : reviews.count
	end

	def search(search)
		
	end

	protected
	def release_date_is_in_the_past
		if release_date.present?
			errors.add(:release_date, "should be in the past") if release_date > Date.today
		end
	end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :user, presence: true
  validates :movie, presence: true
  validates :text, presence: true

  validates :rating_out_of_ten,
  	numericality: {
  		only_integer: true,
  		greater_than_or_equal_to: 1,
  		less_than_or_equal_to: 10
  	}

end

app/models/user.rb
class User < ApplicationRecord
	#virtual attribute added to model
	#so plain txt doesn't get saved in the db
	#only stores the digest version(random hashes)
	has_many :reviews
	has_secure_password

	validates :email , presence: true

	validates :first_name, presence: true

	validates :last_name, presence: true

	validates :password, length: {in: 6..20}, on: :create

	def full_name
		"#{first_name} #{last_name}"
	end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
  	@users = User.all.page(params[:page]).per(10)
  	@user = User.find(session[:user_id])
  	unless @user.is_admin?
  	 redirect_to movies_path, notice: 'Access Denied'
  	end
  end

  def show
  	@user = User.find(session[:user_id])
  	unless @user.is_admin?
  	 redirect_to movies_path, notice: 'Access Denied'
  	end
  end


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  

  def new
  end

  def create
  	if current_user && current_user.is_admin?
  	#give option to user admin view
  	#see all users

  	end 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 #all your controllers inherit from this.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end
  
  #uses an if and an assignment which 
  #finds session id for that user and assigns it to 
  #current user if current user doesn't exist
  #checking then if the user has logged in
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  #increases the scope for your app.
  helper_method :current_user
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
  	@movies = Movie.all
  end

  def show
  	@movie = Movie.find(params[:id])
    
  end

  def new
  	@movie = Movie.new
  end

  def edit
  	@movie = Movie.find(params[:id])
  end

  def create
  	@movie = Movie.new(movie_params)
  	if @movie.save
  		redirect_to movies_path, notice: "Your movie #{@movie.title} was submitted successfully"
  	else
  		render :new
  	end
  end

  def update
  	@movie = Movie.find(params[:id])

  	if @movie.update_attributes(movie_params)
  		redirect_to movies_path
  	else
  		render :edit
  	end
  end

  def destroy
  	@movie = Movie.find(params[:id])
  	@movie.destroy
  	redirect_to movies_path
  end

  protected

  def movie_params
  	params.require(:movie).permit(:title, :director, :description, :image, :runtime_in_minutes, :release_date) 
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :restrict_access
  before_filter :load_movie

	def new
	  	@review = @movie.reviews.build
  end

  def create
  	@review = @movie.reviews.build(review_params)
  	@review.user_id = current_user.id

  	if @review.save
  		redirect_to @movie, notice: "Review created succesfully"
  	else
  		render :new
  	end
  end

  def destroy
    @review = Review.find(params[:id])
    movie_id = @review.movie_id
    @review.destroy
   #specify the controller otherwise it'll try to find the same and create an error
    redirect_to :controller=>'movie', :action=>'show', :id=>movie_id

  end
#from #{@user(params[:id]).full_name}
  

  protected

	def load_movie
		@movie = Movie.find(params[:movie_id])
	end

  def review_params
  	params.require(:review).permit(:text, :rating_out_of_ten)
  end

 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice:"Adios!"
  end
  
  def create
  	user = User.find_by(email: params[:email])
  	if user && user.authenticate(params[:password])

  		session[:user_id] = user.id
  		redirect_to movies_path, notice: "Welcome #{user.first_name}"
      
  	else
      flash.now[:alert] = "Log in failed..."
  		render :new
  	end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save 
      session[:user_id] = @user.id
  		redirect_to movies_path, notice: "Welcome aboard #{@user.first_name}!"
  	else
  		render :new
  	end
  end

  protected
  
  def user_params
  	params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

	def formatted_date(date)
		date.strftime("%b %d, %Y")	
	end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/users/index.html.erb
<h1>Admin::Users#index</h1>

<h3> All users: </h3>
<%= paginate @users%>

<table style="width:100%">
	<tr>
	<th> Full Name</th>
	<th> e-mail</th>
	</tr>
	<% @users.each do |user|%>
	<tr>
		<td><%= user.full_name%> </td>
		<td><%= user.email%></td>
	</tr>
	<% end %>
</br>
</table>

app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>

app/views/layouts/_adminhead.html.erb
<header>

	<% if current_user && current_user.is_admin? %>
		<%= link_to 'admin page', admin_users_path %>
		<%= link_to 'Back home', movies_path %>
	<% end %>

</header>

app/views/layouts/_footer.html.erb
<footer>
	<small>
	<% if current_user %>
		Sign in as <%= current_user.full_name%> <%= link_to "Log out", session_path(current_user), method: :delete%>
	<% else %>
		<%= link_to "Log in", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
	<% end %>
	</small>
	<small>
	<% if current_user && current_user.is_admin? %>
		| <%= link_to 'admin page', admin_users_path %> |
		<%= link_to 'Back home', movies_path %>
	<% end %>
	</small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RottenMangoes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </head>

  <body>

  	<% flash.each do |key,value|%>
  		<%= content_tag(:div, value)%>
  	<% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true } do |f| %>
	<% if @movie.errors.any? %>

	<div>
		<%= pluralize(@movie.errors.count, "error")%> prevented this movie from been added :
		<ul>
			<%= @movie.errors.full_messages.each do |msg|%>
			<li><%= msg %></li>
			<%end%>
		</ul>	
	</div>
<% end %>

	<div>
		<%= f.label :title %><br>
		<%= f.text_field :title%>
	</div>

	<div>
		<%= f.label :release_date %><br>
		<%= f.date_select :release_date%>
	</div>

	<div>
		<%= f.label :director %><br>
		<%= f.text_field :director%>
	</div>

	<div>
		<%= f.label :runtime_in_minutes %><br>
		<%= f.number_field :runtime_in_minutes%>
	</div>

	<div>
		<%= f.label :image %><br>
		<%= f.file_field :image%>
	</div>

	<div>
		<%= f.label :description %><br>
		<%= f.text_area :description%>
	</div>
	<div>
		<%= f.submit "Submit"%>
	</div>

<% end %>

app/views/movies/_searchform.html.erb
<%= form_tag movies_path, method: 'get' do %>
<div>
	<%= label_tag :search, "search for:" %>
	<%= text_field_tag :search, params[:search] %>
	<%= submit_tag "Search", :name => nil %>
</div>
<% end %>

app/views/movies/edit.html.erb
<h1>ROTTEN MANGOES</h1>
<hr>
<%= link_to "Back to movie", movie_path(@movie)%>
<h2> Edit this movie:</h2>
<%= render 'form'%>

app/views/movies/index.html.erb
<h1> Rotten Mangoes </h1>
<hr>
<%= render 'searchform'%>
<h2>All your favourite movies!</h2>

<h1><%= link_to "Submit a movie", new_movie_path %></h1>
</br>

<% @movies.each do |movie| %>

	<%= link_to image_tag(movie.image), movie_path(movie) %>
	<h2><%= link_to movie.title, movie_path(movie)%></h2>

	<h3>Release Date: <%= formatted_date(movie.release_date) %></h3>

	<h4>Dir. <%= movie.director%> | <%= movie.runtime_in_minutes %> minutes</h4>
	<p><%= movie.description %></p></br>
	 Current rating: <strong> <%= movie.review_average %>/10 </strong>
	<hr>
	<% end %>

app/views/movies/new.html.erb
<h1>ROTTEN MANGOES</h1>

<%= link_to "Back to all movies", movies_path %>
<h2> Submit a movie!</h2>
<%= render 'form' %>

app/views/movies/show.html.erb
<h1>ROTTEN MANGOES</h1>
<hr>
<%= link_to "Back to all movies", movies_path %> </br>
<h2><%= @movie.title %>
	(<%= link_to "edit", edit_movie_path(@movie) %>)(<%= link_to "delete", movie_path(@movie), :method => :delete, :"data-confirm" => "You sure :(?" %>)
</h2>
<h3><%= formatted_date(@movie.release_date) %></h3>
<h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes%> minutes
</h4>
<p><%= @movie.description%></p>
<hr>
<h3><em>Reviews of <%= @movie.title %> </em></h3>
<% if current_user %>
	<% @movie.reviews.each do |review| %>
		<p><%= review.text %></p>
		<p><%= review.rating_out_of_ten %>/10</p>
		<small>- <%= review.user.full_name%></small></br>
			<% if current_user.is_admin? %>
			<%= link_to "delete review", movie_review_path(:movie_id=>@movie.id,:id=>review.id), :method => :delete, :"data-confirm" => "Sure?" %>
	

			<% end %>


	<% end %>
	<p><%= link_to "Write a review!", new_movie_review_path(@movie)%></p>
	<% else %>
		<p><%= link_to "log in", new_session_path%> to see reviews and add your own</p>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie)%></br>

<h2> Write a review of <em><%= @movie.title%></em>></h2>

<%= form_for ([@movie, @review]) do |f| %>
	<% if @review.errors.any? %>
		<div>
			<%= pluralize(@review.errors.count, "error")%> prevented the review from being saved:
			<ul>
				<% @review.errors.full_messages.each do |msg|%>
				<li><% msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div>
		<%= f.label :text%>
		<%= f.text_area "text"%>
	</div>

	<div>
		<%= f.label :rating_out_of_ten%>
		<%= f.number_field :rating_out_of_ten%>
	</div>

	<div>
		<%= f.submit "submit" %>
	</div>
<% end %>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |f| %>
	
	<% if @user.errors.any? %>

		<div>
			<%= pluralize(@user.errors.count, 'error')%> prevented the account from been created:
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
		
	<div>	
	<%= f.label :first_name, "First Name"%><br>
	<%= f.text_field :first_name%>
	</div>

	<div>
	<%=f.label :last_name, "Last Name"%><br>
	<%=f.text_field :last_name%>
	</div>

	<div>
	<%= f.label :email%><br>
	<%= f.text_field :email%>
	</div>

	<div>
	<%= f.label :password%><br>
	<%= f.password_field :password%>
	</div>

	<div>
	<%= f.label :password_confirmation %><br>
	<%= f.password_field :password_confirmation %>
	</div>
	<div>
	<%= f.submit "Submit"%>
	</div>

<% end %>